"""V3.19h BUG-1: BIALYSTOK_DISTRICTS data — 28 official osiedli z info.bialystok.pl.

Source: http://www.info.bialystok.pl/osiedla/{1..28}/obiekt.php (2026-04-21 fetched).
Normalized: strip "-parzyste/nieparzyste N-M" suffixes, lowercase.
Regenerate: python3 -m dispatch_v2.build_v319h_districts_data (or tmp generator).

NIE edit manually — regen z oficjalnego źródła per process.
"""

# frozenset for fast "in" lookup per district
BIALYSTOK_DISTRICTS = {
    'Antoniuk': {
        'streets': frozenset({
            'antoniukowska',
            'broniewskiego władysława',
            'choroszczańska',
            'głowackiego bartosza',
            'jana pawła ii',
            'knyszyńska',
            'kolejowa',
            'narewska',
            'ordonówny hanki',
            'owsiana',
            'rondo nauczycieli tajnego nauczania',
            'rondo ronalda reagana',
            'solidarności',
            'stalowa',
            'tuwima juliana',
            'ukośna',
            'wiatrakowa',
            'widok',
            'wierzbowa',
            'wysoka',
            'zielone wzgórze',
            'zwycięstwa',
            'świętokrzyska',
        }),
    },
    'Bacieczki': {
        'streets': frozenset({
            'astronautów',
            'bacieczki',
            'elektronowa',
            'esperantystów',
            'gen. franciszka kleeberga',
            'gen. leopolda okulickiego',
            'gen. stanisława maczka',
            'grabowskiego antoniego',
            'gwiezdna',
            'herberta zbigniewa',
            'ikara',
            'jana pawła ii',
            'jowisza',
            'kazaneckiego wiesława',
            'komarowa władimira',
            'komety',
            'komisji edukacji narodowej',
            'kosmiczna',
            'kołłątaja hugo',
            'ks. witolda pietkuna',
            'mackiewicza józefa',
            'marsa',
            'merkurego',
            'mikołajczyka stanisława',
            'miętowa',
            'nadrzeczna',
            'narodowych sił zbrojnych',
            'neptuna',
            'nmp królowej rodzin',
            'orbitalna',
            'orkana władysława',
            'owocowa',
            'pietkiewicza michała',
            'planetarna',
            'plutona',
            'produkcyjna',
            'rakietowa',
            'rtm. witolda pileckiego',
            'satelitarna',
            'saturna',
            'strażacka',
            'syriusza',
            'szaykowskiej berty',
            'szewko stanisława',
            'tetmajera kazimierza',
            'urana',
            'wenus',
            'wróblewskiego walerego',
        }),
    },
    'Bema': {
        'streets': frozenset({
            'bydgoska',
            'celownicza',
            'gen. józefa bema',
            'kanonierska',
            'kopernika mikołaja',
            'kresowa',
            'lisia',
            'pińska',
            'pogodna',
            'rondo seweryna nowakowskiego prezydenta miasta białegostoku',
            'składowa',
            'tęczowa',
            'wiejska',
            'wojsk ochrony pogranicza',
            'zdrojowa',
        }),
    },
    'Białostoczek': {
        'streets': frozenset({
            '1-szej armii wojska polskiego',
            'białostoczek',
            'bielska',
            'brzeska',
            'buska',
            'gen. władysława andersa',
            'giżycka',
            'gołdapska',
            'grodzieńska',
            'hajnowska',
            'kombatantów',
            'kowieńska',
            'kozłowa',
            'lidzka',
            'olecka',
            'olsztyńska',
            'poleska',
            'przytorowa',
            'płocka',
            'racławicka',
            'radzymińska',
            'rondo krzysztofa jakuba putry wicemarszałka sejmu rp',
            'siemiatycka',
            'sitarska',
            'skidelska',
            'sokólska',
            'suwalska',
            'tysiąclecia państwa polskiego',
            'wileńska',
            'wołkowyska',
            'zagumienna',
            'łańcucka',
            'świsłocka',
        }),
    },
    'Bojary': {
        'streets': frozenset({
            'branickiego jana klemensa',
            'bukowskiego stanisława',
            'chopina fryderyka',
            'część placu dr n. med. a. p. lussy',
            'część ulicy kościelnej',
            'daleka',
            'dobra',
            'elektryczna',
            'gliniana',
            'kamienna',
            'koszykowa',
            'kraszewskiego józefa ignacego',
            'ks. dr. stanisława hałko',
            'modlińska',
            'ogrodowa',
            'orla',
            'pałacowa',
            'piasta',
            'piłsudskiego józefa',
            'poprzeczna',
            'przygodna',
            'próżna',
            'ryska',
            'sienkiewicza henryka',
            'sina',
            'skorupska',
            'sobieskiego jana iii',
            'sowia',
            'sporna',
            'starobojarska',
            'stary rynek',
            'staszica stanisława',
            'szczygla',
            'słomiana',
            'słonimska',
            'towarowa',
            'warszawska',
            'wiktorii',
            'wróbla',
            'wylotna',
            'złota',
            'łąkowa',
            'św. wojciecha',
            'świętojańska',
        }),
    },
    'Centrum': {
        'streets': frozenset({
            'akademicka',
            'armatnia',
            'artyleryjska',
            'biała',
            'blusa',
            'bohaterów getta',
            'botaniczna',
            'branickich',
            'branickiego jana klemensa',
            'cieszyńska',
            'cygańska',
            'czysta',
            'częstochowska',
            'dr ireny białówny',
            'dąbrowskiego jana henryka',
            'elekryczna',
            'grajewska',
            'grochowa',
            'grunwaldzka',
            'jana pawła ii',
            'józefa blicharskiego',
            'kalinowskiego konstantego',
            'kijowska',
            'kilińskiego jana',
            'kościałkowskiego',
            'kościelna',
            'kościuszki',
            'krakowska',
            'ks. adama abramowicza',
            'legionowa',
            'liniarskiego władysława',
            'lipowa',
            'malmeda icchoka',
            'marjańskiego józefa',
            'marszałka józefa piłsudskiego',
            'mazowiecka',
            'mickiewicza adama',
            'młynowa',
            'niepodległości im. romana dmowskiego',
            'nowy świat',
            'odeska',
            'ołowiana',
            'piotrkowska',
            'piękna',
            'piłsudskiego józefa',
            'poleska',
            'prezydenta ryszarda kaczorowskiego',
            'proletariacka',
            'przejazd',
            'północna',
            'sienkiewicza henryka',
            'sienny rynek',
            'skłodowskiej-curie marii',
            'spółdzielcza',
            'suraska',
            'tadeusza kielanowskiego',
            'uniwersytecki',
            'waryńskiego ludwika',
            'włókiennicza',
            'zakochanych',
            'zamenhofa ludwika',
            'św. mikołaja',
            'św. rocha',
            'świętojańska',
            'żabia',
            'żytnia',
        }),
    },
    'Dojlidy': {
        'streets': frozenset({
            'bartnicza',
            'bobrów',
            'bociania',
            'borsucza',
            'ciołkowskiego konstantego',
            'dojlidy fabryczne',
            'dojnowska',
            'jaskółcza',
            'jelenia',
            'karpińskiego franciszka',
            'kormoranów',
            'krecia',
            'królicza',
            'ks. stanisława suchowolca',
            'kuronia jacka',
            'kuropatwia',
            'michałowskiego jana',
            'mickiewicza adama',
            'myśliwska',
            'niedźwiedzia',
            'nowowarszawska',
            'pawia',
            'plażowa',
            'ptasia',
            'rondo 10 pułku ułanów litewskich',
            'rysia',
            'sarnia',
            'sokola',
            'stawowa',
            'strusia',
            'szpacza',
            'sępia',
            'słowicza',
            'tygrysia',
            'wiadukt',
            'wiewiórcza',
            'wilcza',
            'zajęcza',
            'łabędzia',
            'łosia',
            'św proroka eliasza',
            'żubrów',
            'żurawia',
            'żółwia',
        }),
    },
    'Dojlidy Górne': {
        'streets': frozenset({
            'agawy',
            'albatrosa',
            'algebraiczna',
            'astrów',
            'azaliowa',
            'bajeczna',
            'berberysowa',
            'browarowa',
            'brzegowa',
            'brzoskwiniowa',
            'bukszpanowa',
            'busolowa',
            'cukiniowa',
            'cumownicza',
            'cyfrowa',
            'cytrynowa',
            'czereśniowa',
            'daliowa',
            'deszczowa',
            'dodatnia',
            'dojlidy górne',
            'dokerów',
            'dolina stawów',
            'drzewna',
            'dzwonkowa',
            'edukacyjna',
            'falowa',
            'fiołkowa',
            'fregatowa',
            'funkcyjna',
            'geometryczna',
            'gerberowa',
            'gminna',
            'goździkowa',
            'grabowa',
            'górna',
            'halicka',
            'helska',
            'hiacyntowa',
            'holownicza',
            'irysowa',
            'jachtowa',
            'jaskrów',
            'jastrzębia',
            'kadłubowa',
            'kaktusowa',
            'kameliowa',
            'kanarkowa',
            'kapitańska',
            'kolonia dojlidy',
            'kolorowa',
            'komandorska',
            'koperkowa',
            'kotwicowa',
            'kowalska',
            'kraski',
            'krokusowa',
            'kryniczna',
            'krzywa',
            'leśna polana',
            'leśne echa',
            'leśnej jagody',
            'liniowa',
            'logarytmiczna',
            'lubczykowa',
            'maciejki',
            'macierzanki',
            'majowa',
            'malwowa',
            'margerytki',
            'marynarska',
            'masztowa',
            'matematyczna',
            'mazurska',
            'mewy',
            'michałowe pole',
            'milowa',
            'mnożna',
            'morska',
            'motyla',
            'nad potokiem',
            'narcyzowa',
            'nasienna',
            'nasturcjowa',
            'niezapominajki',
            'okrętowa',
            'ordynacka',
            'ostróżki',
            'pagórkowa',
            'paprociowa',
            'pelargonii',
            'perłowa',
            'pierwiastkowa',
            'piracka',
            'pod lasem',
            'podmokła',
            'pokładowa',
            'poranna',
            'posejdona',
            'potokowa',
            'promowa',
            'przelotowa',
            'przepiórki',
            'pszeniczna',
            'pływacka',
            'rejsowa',
            'rozmarynowa',
            'ruczajowa',
            'rybitwy',
            'rzeczna',
            'sasanki',
            'sezamkowa',
            'sieciowa',
            'sikorki',
            'skowronkowa',
            'solnicka',
            'sterowa',
            'stoczni gdańskiej',
            'stokrotki',
            'strumykowa',
            'szafirowa',
            'szkwałowa',
            'sztormowa',
            'tulipanowa',
            'ułamkowa',
            'wigierska',
            'wiosłowa',
            'wodna',
            'wolińska',
            'zabłudowska',
            'zagórki',
            'zalesie',
            'zatokowa',
            'zawilców',
            'zielona',
            'zielone jabłuszko',
            'św. jana chrzciciela',
            'żeglarska',
        }),
    },
    'Dziesięciny I': {
        'streets': frozenset({
            'akacjowa',
            'antoniuk fabryczny',
            'brzozowa',
            'bukowa',
            'cedrowa',
            'cisowa',
            'cyprysowa',
            'daktylowa',
            'dziesięciny',
            'dębowa',
            'figowa',
            'gajowa',
            'gen. stanisława maczka',
            'gen. zygmunta berlinga',
            'jaworowa',
            'jałowcowa',
            'jaśminowa',
            'jesionowa',
            'jodłowa',
            'kalinowa',
            'kasztanowa',
            'kokosowa',
            'leszczynowa',
            'malinowa',
            'morelowa',
            'oliwkowa',
            'orzechowa',
            'palmowa',
            'wiązowa',
            'wrzosowa',
            'św. kazimierza',
        }),
    },
    'Dziesięciny II': {
        'streets': frozenset({
            'antoniuk fabryczny',
            'gajowa',
            'gen. stanisława maczka',
            'gen. zygmunta berlinga',
            'jarzębinowa',
            'oliwkowa',
            'palmowa',
            'porzeczkowa',
            'wiśniowa',
            'zagórna',
            'św. kazimierza-budynek 12',
        }),
    },
    'Jaroszówka': {
        'streets': frozenset({
            'agatki',
            'aliny',
            'armii ludowej',
            'bagnówka-kolonia',
            'balladyny',
            'batorego stefana',
            'baśniowa',
            'berezyńska',
            'biebrzańska',
            'boruty',
            'bursztynowa',
            'bystrzycka',
            'błękitna',
            'chodkiewicza karola',
            'cicha',
            'cypiska',
            'czarnej hańczy',
            'czerwonego kapturka',
            'diamentowa',
            'domeyki ignacego',
            'dożynkowa',
            'duracza teodora',
            'dyngusowa',
            'dźwińska',
            'familijna',
            'gaskiewicza dymitra',
            'gedymina',
            'gen. stefana grota-roweckiego',
            'gen. władysława andersa',
            'goszczyńskiego seweryna',
            'gościnna',
            'gwiazdkowa',
            'hanki',
            'hałki stanisława',
            'hubala',
            'im. arch. krystyny drewnowskiej',
            'jacka',
            'jagiełły władysława',
            'janosika',
            'jaroszówka',
            'jaspisowa',
            'jutrzenki',
            'jęczmienna',
            'kameralna',
            'karpowicza aleksandra',
            'kasprzaka marcina',
            'kirkora',
            'kopciuszka',
            'koralowa',
            'kordiana',
            'kościńskiego zygmunta',
            'krasickiego janka',
            'krasnoludków',
            'krzyżowa',
            'króla zygmunta augusta',
            'królowej bony',
            'królowej jadwigi',
            'księcia kiejstuta',
            'księcia witolda',
            'kłosowa',
            'lazurowa',
            'lelewela joachima',
            'malachitowa',
            'modra',
            'nadbużańska',
            'niemeńska',
            'notecka',
            'obłoków',
            'odrzańska',
            'ondraszka',
            'partyzantów',
            'pietrasze',
            'plastusia',
            'prypecka',
            'przytulna',
            'radosna',
            'raginisa władysława',
            'rondo krzysztofa jakuba putry wicemarszałka sejmu rp',
            'rumcajsa',
            'rycerska',
            'róży wiatrów',
            'sawickiej eweliny',
            'skalna',
            'skarżyńskiego stanisława',
            'skrzatów',
            'staffa leopolda',
            'szczęśliwa',
            'szmaragdowa',
            'topazowa',
            'trawiasta',
            'tysiąclecia państwa polskiego',
            'uśmiechu',
            'wallenroda konrada',
            'warneńczyka władysława',
            'wasilkowska',
            'wiankowa',
            'wiklinowa',
            'wilejki',
            'wiślana',
            'wybickiego józefa',
            'wymarzona',
            'wysockiego władysława',
            'węgierki aleksandra',
            'zapolskiej gabrieli',
            'zgoda',
            'ziółkowskiego józefa',
            'zygmunta starego',
            'łokietka władysława',
            'łącznikowa',
            'św. maksymiliana marii kolbego',
            'żółkiewskiego stanisława',
        }),
    },
    'Kawaleryjskie': {
        'streets': frozenset({
            'braterska',
            'ciołkowskiego konstantego',
            'dzielna',
            'gen. józefa sowińskiego',
            'gołębia',
            'grażyny',
            'harcerska',
            'horodniańska',
            'kawaleryjska',
            'kominek',
            'kredytowa',
            'krucza',
            'kręta',
            'ks. abp edwarda kisiela',
            'mrówcza',
            'nowa',
            'pajęcza',
            'pancerna',
            'plater emilii',
            'pogodna',
            'południowa',
            'pracownicza',
            'pszczela',
            'pułaskiego kazimierza',
            'rondo 10 pułku ułanów litewskich',
            'równa',
            'strzelecka',
            'sławińskiego witolda',
            'słoneczna',
            'ułańska',
            'wiejska',
            'wiosenna',
            'wspólna',
            'zachodnia',
            'zapiecek',
            'zielna',
            'żeromskiego stefana',
        }),
    },
    'Leśna Dolina': {
        'streets': frozenset({
            'armii krajowej',
            'bacieczki',
            'batalionów chłopskich',
            'gen. władysława sikorskiego',
            'grzeczna',
            'hotelowa',
            'jana pawła ii',
            'ks. jerzego popiełuszki',
            'miłosna',
            'niska',
            'powstańców',
            'przyjazna',
            'sympatyczna',
            'szarych szeregów',
            'św. andrzeja boboli',
        }),
    },
    'Mickiewicza': {
        'streets': frozenset({
            '11-go listopada',
            'augustowska',
            'bednarska',
            'białowieska',
            'bracka',
            'branickiego jana klemensa',
            'brańska',
            'cienista',
            'ciołkowskiego konstantego',
            'dojlidzka',
            'drewniana',
            'folwarczna',
            'gdańska',
            'gliwicka',
            'grottgera artura',
            'hoża',
            'jagiellońska',
            'jagodowa',
            'kawaleryjska',
            'konopnickiej marii',
            'kołodziejska',
            'księżycowa',
            'kwiatowa',
            'letniska',
            'lwowska',
            'malinowskiego franciszka',
            'mickiewicza adama',
            'modrzewiowa',
            'murarska',
            'nowowarszawska',
            'orzeszkowej elizy',
            'parkowa',
            'pod krzywą',
            'podleśna',
            'prusa bolesława',
            'przemysłowa',
            'romantyczna',
            'saska',
            'szczecińska',
            'słowackiego juliusza',
            'urocza',
            'wiosenna',
            'wołodyjowskiego michała',
            'zaułek bracki',
            'zaułek zakopiański',
            'zwierzyniecka',
            'ładna',
            'łódzka',
            'śląska',
            'świerkowa',
            'świętego pio',
            'świętojańska',
            'żwirki i wigury',
        }),
    },
    'Młodych': {
        'streets': frozenset({
            'asnyka adama',
            'dąbrowskiej marii',
            'gałczyńskiego konstantego ildefonsa',
            'gruntowa',
            'hetmańska',
            'jana pawła ii',
            'kobryńska',
            'kolejowa',
            'konduktorska',
            'kossak-szczuckiej zofii',
            'kruczkowskiego leona',
            'marczukowska',
            'nałkowskiej zofii',
            'promienna',
            'prowiantowa',
            'płaska',
            'reymonta władysława',
            'rondo ronalda reagana',
            'spokojna',
            'zwycięstwa',
            'ślusarska',
        }),
    },
    'Nowe Miasto': {
        'streets': frozenset({
            'cementowa',
            'dubois stanisława',
            'ekologiczna',
            'handlowa',
            'hurtowa',
            'ignacego j. paderewskiego',
            'kawaleryjska',
            'krucza',
            'magazynowa',
            'oboźna',
            'octowa',
            'pułaskiego kazimierza',
            'rondo 10 pułku ułanów litewskich',
            'rzymowskiego wincentego',
            'sejneńska',
            'składowa',
            'starosielce',
            'sławińskiego witolda',
            'transportowa',
            'wapienna',
            'wiadukt',
            'zachodnia',
            'zakątek',
            'łodzińskiego piotra',
            'ścianka',
            'św. kingi',
            'żeromskiego stefana',
        }),
    },
    'Piaski': {
        'streets': frozenset({
            'akademicka',
            'bułgarska',
            'czackiego tadeusza',
            'krasińskiego zygmunta',
            'legionowa',
            'mazowiecka',
            'olszowa',
            'prezydenta ryszarda kaczorowskiego',
            'prosta',
            'przekątna',
            'rybny rynek',
            'skłodowskiej-curie marii',
            'sportowa',
            'sucha',
            'szpitalna',
            'targowa',
            'waszyngtona jerzego',
            'wesoła',
            'wiejska',
            'wojskowa',
            'wołodyjowskiego michała',
            'zwierzyniecka',
            'świerkowa',
            'żelazna',
        }),
    },
    'Piasta I': {
        'streets': frozenset({
            'chrobrego bolesława',
            'czarnieckiego stefana',
            'część ulicy wołyńskiej',
            'daleka',
            'ducha świętego',
            'grzybowa',
            'ks. st. andrukiewicza',
            'mieszka i',
            'piasta',
            'piastowska',
            'skorupska',
            'spacerowa',
            'sybiraków',
            'towarowa',
        }),
    },
    'Piasta II': {
        'streets': frozenset({
            'branickiego jana klemensa',
            'chopina fryderyka',
            'chrobrego bolesława',
            'orzeszkowej elizy',
            'piastowska',
            'staszica stanisława',
            'warszawska',
            'św. wojciecha',
            'świętojańska',
        }),
    },
    'Przydworcowe': {
        'streets': frozenset({
            'angielska',
            'bażantarska',
            'bliska',
            'bohaterów monte cassino',
            'brukowa',
            'chełmska',
            'ciechanowska',
            'cieszyńska',
            'czarna',
            'gen. józefa bema',
            'grunwaldzka',
            'jasna',
            'kardynała stefana wyszyńskiego',
            'kielecka',
            'kijowska',
            'kochanowskiego jana',
            'kopernika mikołaja',
            'krakowska',
            'krótka',
            'kurpiowska',
            'lubelska',
            'marmurowa',
            'mazowiecka',
            'mohylowska',
            'mławska',
            'młynowa',
            'opatowska',
            'ostrowiecka',
            'prezydenta ryszarda kaczorowskiego',
            'przechodnia',
            'rondo seweryna nowakowskiego prezydenta miasta białegostoku',
            'sosnowa',
            'stołeczna',
            'sukienna',
            'szczuczyńska',
            'toruńska',
            'warecka',
            'witebska',
            'łomżyńska',
            'łukowska',
            'św. rocha',
            'żółta',
        }),
    },
    'Sienkiewicza': {
        'streets': frozenset({
            'chmielna',
            'ciepła',
            'fabryczna',
            'inwalidów wojennych',
            'jagienki',
            'jurowiecka',
            'nowogródzka',
            'ogrodowa',
            'poleska',
            'sienkiewicza henryka',
            'wyzwolenia',
            'wąska',
        }),
    },
    'Skorupy': {
        'streets': frozenset({
            'baranowicka',
            'branickiego jana klemensa',
            'cała',
            'ceramiczna',
            'ciesielska',
            'ciołkowskiego konstantego',
            'dojlidy fabryczne',
            'dojnowska',
            'geodetów',
            'gospodarska',
            'gródecka',
            'górnicza',
            'hutnicza',
            'iglasta',
            'juranda',
            'kajki michała',
            'kmicica',
            'kolonijna',
            'korzeniowskiego józefa konrada',
            'kujawska',
            'kąpielowa',
            'leśna',
            'liściasta',
            'lubuska',
            'małopolska',
            'mokra',
            'naftowa',
            'nowatorska',
            'nowowarszawska',
            'obrębowa',
            'opolska',
            'piaskowa',
            'piasta',
            'piastowska',
            'pionowa',
            'plażowa',
            'podłużna',
            'pomorska',
            'pozioma',
            'przejściowa',
            'puchatka',
            'rondo kawalina mikołaja',
            'rzeszowska',
            'serwitutowa',
            'sobolewska',
            'sowlańska',
            'stawowa',
            'turystyczna',
            'wakacyjna',
            'warmińska',
            'wczasowa',
            'wielkopolska',
            'wołyńska',
            'zagłoby',
            'zaułek kłodzki',
            'zaułek olsztyński',
            'zaułek podhalański',
            'zaułek podlaski',
            'zaułek łęczycki',
            'zaściańska',
            'zbożowa',
            'zdrowa',
            'zuchów',
            'łużycka',
            'śmiała',
            'źródlana',
        }),
    },
    'Starosielce': {
        'streets': frozenset({
            'barszczańska',
            'bałtycka',
            'belgijska',
            'białoruska',
            'chorwacka',
            'czeska',
            'duńska',
            'elewatorska',
            'estońska',
            'fińska',
            'francuska',
            'grecka',
            'hiszpańska',
            'holenderska',
            'irlandzka',
            'jana pawła ii',
            'klepacka',
            'klonowa',
            'korycińska',
            'krzywoń anieli',
            'ks. jerzego popiełuszki',
            'ks. pawła grzybowskiego',
            'ks. stefana girstuna',
            'kubańska',
            'lawendowa',
            'letnia',
            'litewska',
            'meksykańska',
            'miodowa',
            'mongolska',
            'niepodległości',
            'niewodnicka',
            'norweska',
            'nowosielska',
            'okrzei stefana',
            'pajkerta edwarda',
            'pazińskiego romana',
            'polowa',
            'polska',
            'portugalska',
            'reja mikołaja',
            'rumuńska',
            'rybnika aleksandra',
            'serbska',
            'serwisowa',
            'skandynawska',
            'szkolna',
            'szwajcarska',
            'słowacka',
            'słoweńska',
            'techniczna',
            'troczewskiego zbigniewa',
            'turowskiego józefa',
            'ubocze',
            'ukraińska',
            'warsztatowa',
            'watykańska',
            'wenecka',
            'wiedeńska',
            'wietnamska',
            'wrocławska',
            'węgierska',
            'włoska',
            'zimowa',
            'łotewska',
            'św. andrzeja boboli',
        }),
    },
    'Słoneczny Stok': {
        'streets': frozenset({
            'gen. władysława sikorskiego',
            'hetmańska',
            'ks. jerzego popiełuszki',
            'marczukowska',
            'skrajna',
            'stroma',
            'upalna',
            'wincentego witosa',
        }),
    },
    'Wygoda': {
        'streets': frozenset({
            '27 lipca',
            '42 pułku piechoty',
            'antoniewicza jerzego',
            'bacewicz grażyny',
            'baczyńskiego krzysztofa kamila',
            'bagienna',
            'bagnowska',
            'banachiewicza tadeusza',
            'białkowskiego karola',
            'bogusławskiego wojciecha',
            'brodowicza zygmunta',
            'brzechwy jana',
            'brzostowskiego karola',
            'chabrowa',
            'chełmońskiego józefa',
            'chętnika adama',
            'chłopska',
            'ciasna',
            'ciołkowskiego konstantego',
            'dolistowska',
            'drzymały wojciecha',
            'dunikowskiego xawerego',
            'fabryczna',
            'fredry aleksandra',
            'gen. władysława andersa',
            'glogera zygmunta',
            'gogola mikołaja',
            'gorbatowa aleksandra',
            'gorkiego maksyma',
            'gradowa',
            'harnasiów',
            'honorowych krwiodawców',
            'jaracza stefana',
            'jesienna',
            'kantora tadeusza',
            'kapralska',
            'karnego alfonsa',
            'karłowicza mieczysława',
            'kluka jana krzysztofa',
            'komunalna',
            'korczaka janusza',
            'kosińskiego konstantego',
            'kościałkowskiego zyndrama',
            'krańcowa',
            'ks. aleksandra syczewskiego',
            'księcia józefa poniatowskiego',
            'kątowa',
            'leca stanisława',
            'leńskiego juliana',
            'ludowa',
            'makowa',
            'makuszyńskiego kornela',
            'malinowskiego franciszka',
            'marcinkiewicza józefa',
            'matejki jana',
            'mjr henryka sucharskiego',
            'moniuszki stanisława',
            'młoda',
            'niemcewicza juliana ursyna',
            'norwida cypriana kamila',
            'nowakowskiego seweryna',
            'nowowiejskiego feliksa',
            'obrońców westerplatte',
            'oczki wojciecha',
            'odległa',
            'ofiar majdanka',
            'ogińskiego michała kleofasa',
            'paska jana chryzostoma',
            'pieczurki',
            'pionierska',
            'pola wincentego',
            'poleska',
            'prądzyńskiego ignacego',
            'puchalskiego karola',
            'pusta',
            'puszkina aleksandra',
            'pułkowa',
            'raginisa władysława',
            'robotnicza',
            'rodzinna',
            'rolna',
            'rubinowicza wojciecha',
            'sadowa',
            'sandomierska',
            'saperska',
            'sekcyjna',
            'siedleckiego wacława',
            'sielska',
            'siewna',
            'skargi piotra',
            'stepowa',
            'struga andrzeja',
            'synów pułku',
            'szamańskiego bolesława',
            'szymanowskiego karola',
            'sąsiedzka',
            'tarasowa',
            'tarnowska',
            'traugutta romualda',
            'trawiasta',
            'ustronna',
            'warzywna',
            'wasilkowska',
            'wańkowicza melchiora',
            'wieniawskiego henryka',
            'wschodnia',
            'wyki kazimierza',
            'wyspiańskiego stanisława',
            'wąska',
            'węglowa',
            'włościańska',
            'zacisze',
            'zana tomasza',
            'zawadzka',
            'ziemska',
            'zoli emila',
            'ściegiennego piotra',
            'środkowa',
            'św. józefa',
            'żeleńskiego boya',
            'żmichowskiej narcyzy',
            'żniwna',
            'żołnierska',
            'żwirowa',
            'żyzna',
        }),
    },
    'Wysoki Stoczek': {
        'streets': frozenset({
            'antoniuk fabryczny',
            'blokowa',
            'budowlana',
            'bystra',
            'dworska',
            'działkowa',
            'dziecinna',
            'długa',
            'fiedorowicza konrada',
            'gromadzka',
            'jana pawła ii',
            'konstytucji 3 maja',
            'kołłątaja hugo',
            'ks. abp r. jałbrzykowskiego',
            'ogrodniczki',
            'opatrzności bożej',
            'pochyła',
            'pomiarowa',
            'przycmentarna',
            'rzemieślnicza',
            'scaleniowa',
            'studzienna',
            'swobodna',
            'szeroka',
            'wysoki stoczek',
            'łagodna',
        }),
    },
    'Zawady': {
        'streets': frozenset({
            'bohuna',
            'chmielowa',
            'chłodna',
            'dolna',
            'gen. franciszka kleeberga',
            'gen. stanisława maczka',
            'jana skrzetuskiego',
            'jana zamoyskiego',
            'janusza radziwiłła',
            'kaszmirowa',
            'końcowa',
            'kryształowa',
            'liliowa',
            'lodowa',
            'oleńki',
            'orląt lwowskich',
            'pawła sapiehy',
            'polna',
            'produkcyjna',
            'przędzalniana',
            'szosa ełcka',
            'szyszkowa',
            'tadeusz rejtana',
            'tkacka',
            'tysiąclecia państwa polskiego',
            'wspaniała',
            'zawady',
            'śnieżna',
        }),
    },
    'Zielone Wzgórza': {
        'streets': frozenset({
            'część ulicy hetmańskiej',
            'konwaliowa',
            'ks. jerzego popiełuszki',
            'lniana',
            'magnoliowa',
            'niepodległości',
            'rumiankowa',
            'różana',
            'storczykowa',
            'słonecznikowa',
            'wrocławska',
            'zielonogórska',
        }),
    },
}

# Lista outside-city zones wykrywanych przez miejscowość field w CSV/state.
# V3.26 STEP 5 (R-06): dodane Olmonty + Izabelin (Adrian ACK 23.04 — both SE
# podbiałostockie wsie, real deliveries widoczne w geocode_cache+orders_state).
BIALYSTOK_OUTSIDE_CITY_ZONES = frozenset({
    'Choroszcz', 'Wasilków', 'Kleosin', 'Ignatki-osiedle',
    'Olmonty', 'Izabelin',
})


# ============================================================
# V3.26 STEP 5 (R-06 MULTI-STOP-TRAJECTORY)
# ============================================================
# Quadrant assignment per district — 6 buckets (N/E/SE/SW/W/CENTER).
# Adrian ACK 2026-04-23 23:30: Wasilków→E, S rozbite na SE/SW, NEW Olmonty/Izabelin SE.
# CENTER buckets non-opposite to anything (zawsze SIMILAR via adjacency lub SIDEWAYS).
QUADRANT_BY_DISTRICT = {
    # NORTH
    'Antoniuk': 'N', 'Bacieczki': 'N', 'Białostoczek': 'N',
    'Dziesięciny I': 'N', 'Dziesięciny II': 'N',
    'Wysoki Stoczek': 'N', 'Zawady': 'N',
    'Choroszcz': 'N', 'Młodych': 'N',
    # EAST (Adrian: Wasilków → E, NIE N)
    'Bojary': 'E', 'Jaroszówka': 'E', 'Sienkiewicza': 'E',
    'Wygoda': 'E', 'Skorupy': 'E',
    'Wasilków': 'E',
    # SOUTH-EAST (Adrian rozbicie S 23.04: Dojlidy*, Olmonty, Izabelin)
    'Dojlidy': 'SE', 'Dojlidy Górne': 'SE',
    'Olmonty': 'SE', 'Izabelin': 'SE',
    # SOUTH-WEST (Adrian rozbicie S 23.04: Bema, Nowe Miasto, Ignatki, Kleosin, Kawaleryjskie)
    'Bema': 'SW', 'Nowe Miasto': 'SW',
    'Ignatki-osiedle': 'SW', 'Kleosin': 'SW', 'Kawaleryjskie': 'SW',
    # WEST
    'Leśna Dolina': 'W', 'Słoneczny Stok': 'W',
    'Starosielce': 'W', 'Zielone Wzgórza': 'W',
    # CENTER (always neutral — never OPPOSITE)
    'Centrum': 'CENTER', 'Mickiewicza': 'CENTER',
    'Piaski': 'CENTER', 'Piasta I': 'CENTER',
    'Piasta II': 'CENTER', 'Przydworcowe': 'CENTER',
}

# OPPOSITE pairs (set of frozensets) — explicit dla deterministic classification.
# N ↔ SE / SW (kurier z północy → drop na południu = krzyż miasta)
# E ↔ W (klasyczne wschód-zachód)
# Inne pary cross-quadrant = SIDEWAYS (one-step over).
_OPPOSITE_QUADRANT_PAIRS = frozenset({
    frozenset({'N', 'SE'}),
    frozenset({'N', 'SW'}),
    frozenset({'E', 'W'}),
})


def classify_trajectory(drop_district, pickup_district, adjacency_map):
    """V3.26 R-06 trajectory classifier.

    Args:
        drop_district: name z BIALYSTOK_DISTRICTS / BIALYSTOK_OUTSIDE_CITY_ZONES
                       lub 'Unknown'/None.
        pickup_district: same.
        adjacency_map: BIALYSTOK_DISTRICT_ADJACENCY (z common.py).

    Returns:
        (relation, detail) tuple gdzie relation ∈
        {'SAME', 'SIMILAR', 'SIDEWAYS', 'OPPOSITE', 'UNKNOWN'}.
        detail = string opisujący rationale ('Unknown drop' / 'adj' / 'opp N↔SE' etc.)
    """
    if not drop_district or drop_district == 'Unknown':
        return ('UNKNOWN', 'Unknown drop district')
    if not pickup_district or pickup_district == 'Unknown':
        return ('UNKNOWN', 'Unknown pickup district')
    # SAME = identical
    if drop_district == pickup_district:
        return ('SAME', f'same district: {drop_district}')
    # SIMILAR = adjacency map hit (oba kierunki — symmetry)
    drop_adj = adjacency_map.get(drop_district, set())
    pickup_adj = adjacency_map.get(pickup_district, set())
    if pickup_district in drop_adj or drop_district in pickup_adj:
        return ('SIMILAR', f'adjacent: {drop_district}↔{pickup_district}')
    # CENTER touch — never OPPOSITE (zawsze "by drodze")
    drop_q = QUADRANT_BY_DISTRICT.get(drop_district)
    pickup_q = QUADRANT_BY_DISTRICT.get(pickup_district)
    if drop_q is None or pickup_q is None:
        # Outside quadrant map → UNKNOWN classification (defensive)
        return ('UNKNOWN', f'unmapped quadrant: drop={drop_district} pickup={pickup_district}')
    if drop_q == 'CENTER' or pickup_q == 'CENTER':
        return ('SIDEWAYS', f'center-touch: {drop_q}↔{pickup_q} (no adjacency)')
    # OPPOSITE explicit pairs
    if frozenset({drop_q, pickup_q}) in _OPPOSITE_QUADRANT_PAIRS:
        return ('OPPOSITE', f'opposite: {drop_q}↔{pickup_q}')
    # Default = SIDEWAYS (cross-quadrant, ale nie opposite)
    return ('SIDEWAYS', f'sideways: {drop_q}↔{pickup_q}')
