#!/usr/bin/env python3
"""Authoritative LIVE values of every calibration constant/flag (runtime, not file default).
Imports dispatch_v2.common (sees code defaults; systemd env confirmed to override NONE of these)
and reads flags.json via C.flag where available. READ-ONLY. Run with dispatch venv."""
import sys, json
sys.path.insert(0, "/root/.openclaw/workspace/scripts")
from dispatch_v2 import common as C  # noqa

FLAGS = json.load(open("/root/.openclaw/workspace/scripts/flags.json"))

CONSTS = {
 "LOAD/SCARCITY": ["AUTO_ASSIGN_MIN_POOL_FEASIBLE", "LOADGOV_TIGHTEN_AT", "LOADGOV_DEFENSIVE_AT",
    "LOADGOV_REARM_AT", "LOADGOV_BAG_MIN", "LOADGOV_BAG_PENALTY", "LOADGOV_EWMA_TAU_MIN",
    "LOADGOV_ORDER_FRESH_H", "SOON_FREE_MAX_MIN", "REPO_COST_MAX_PENALTY"],
 "A+B EXTEND/DEFER/PICKUP": ["LATE_PICKUP_HARD_MAX_MIN", "LATE_PICKUP_SOFT_FREE_MIN",
    "LATE_PICKUP_SOFT_COEFF", "LATE_PICKUP_SOFT_CAP", "OBJ_PICKUP_FRESHNESS_THRESHOLD_MIN",
    "OBJ_PICKUP_FRESHNESS_PENALTY_COEFF", "OBJ_DELIVERY_FOOD_AGE_COEFF", "PICKUP_SPAN_SOFT_START_MIN",
    "PICKUP_SPAN_SOFT_PENALTY_PER_MIN", "RESTAURANT_WAIT_SOFT_MIN", "RESTAURANT_WAIT_PENALTY_PER_MIN",
    "FREEZE_LEAD_MIN", "EARLY_BIRD_THRESHOLD_MIN", "V327_PICKUP_TIME_WINDOW_CLOSE_MIN"],
 "R6 / 35-MIN": ["BAG_TIME_HARD_MAX_MIN", "BAG_TIME_SOFT_MIN", "BAG_TIME_SOFT_PENALTY_PER_MIN",
    "BAG_TIME_DANGER_MIN", "BAG_TIME_DANGER_PENALTY_PER_MIN", "BAG_TIME_SUM_PENALTY_PER_MIN",
    "BAG_TIME_MAX_PENALTY_PER_MIN", "BAG_TIME_FIFO_TIE_PENALTY"],
 "C DIRECTION": ["V326_R06_BONUS_SAME", "V326_R06_BONUS_SIMILAR", "V326_R06_PENALTY_SIDEWAYS",
    "V326_R06_PENALTY_OPPOSITE", "PO_DRODZE_DIST_KM", "PO_DRODZE_TIME_DIFF_MIN", "PO_DRODZE_MAX_INTERVENING",
    "RETURN_TO_RESTAURANT_PENALTY", "RETURN_TO_RESTAURANT_SAME_KM", "RETURN_TO_RESTAURANT_GROUP_TOL_MIN",
    "CARRY_CHAIN_PENALTY_COEFF", "CARRY_CHAIN_ETA_THRESHOLD_MIN", "CARRY_CHAIN_HARD_REJECT_STOPS",
    "R5_DETOUR_PENALTY_PER_KM", "BUNDLE_FIT_W_COS", "BUNDLE_FIT_THERMAL_FREE_MIN", "BUNDLE_FIT_THERMAL_PER_MIN",
    "BUNDLE_FIT_SPAN_FREE_MIN", "BUNDLE_FIT_SPAN_PER_MIN"],
 "D FASTEST/ETA/DWELL": ["DWELL_PICKUP_FLAT_MIN", "DWELL_DEFAULT_MIN", "GPS_AGE_DISCOUNT_FREE_MIN",
    "GPS_AGE_DISCOUNT_PER_MIN", "GPS_AGE_DISCOUNT_CAP", "V3273_WAIT_COURIER_THRESHOLD_MIN",
    "V3273_WAIT_COURIER_FIRST_STEP_PENALTY", "V3273_WAIT_COURIER_PER_MIN_PENALTY",
    "V3273_WAIT_COURIER_HARD_REJECT_MIN", "V326_OR_TOOLS_TIME_LIMIT_MS", "V327_MIN_OR_TOOLS_BAG_AFTER"],
}

FLAGNAMES = ["ENABLE_FLEET_LOAD_GOVERNOR", "ENABLE_SOON_FREE_CANDIDATE", "ENABLE_REPO_COST_LIVE",
 "ENABLE_REPO_COST_SHADOW", "ENABLE_ALWAYS_PROPOSE_ON_SATURATION", "ENABLE_LATE_PICKUP_HARD_GATE",
 "ENABLE_LATE_PICKUP_TIERING_SCORE_FIRST", "ENABLE_OBJ_PICKUP_FRESHNESS", "ENABLE_OBJ_DELIVERY_FOOD_AGE",
 "ENABLE_OBJ_DELIVERY_FOOD_AGE_SHADOW", "ENABLE_OBJ_R6_SOFT_DEADLINE", "ENABLE_ETA_QUANTILE_R6_BAGCAP",
 "ENABLE_OBJ_F3_BEST_EFFORT_R6_KOORD", "ENABLE_BAG_TIME_FAIRNESS_SCORING", "ENABLE_R6_DANGER_ZONE_PENALTY",
 "ENABLE_R1_WAVE_SCOPED_DIRECTIONALITY", "ENABLE_R1_CORRIDOR_GRADIENT", "ENABLE_R1_PROGRESSIVE_CLIP",
 "ENABLE_R_RETURN_TO_RESTAURANT_VETO", "ENABLE_CARRY_CHAIN_PENALTY", "ENABLE_R5_PICKUP_DETOUR_PENALTY",
 "ENABLE_GPS_AGE_DISCOUNT", "ENABLE_V327_BUG_FIXES_BUNDLE", "ENABLE_BUNDLE_VALUE_SCORING",
 "ENABLE_E2_PLN_AB", "ENABLE_PLN_RESORT_WITHIN_TIER", "ENABLE_PLN_QUALITY_AWARE",
 "ENABLE_OBJM_LEXR6_SELECT_SHADOW", "ENABLE_PACZKA_R6_THERMAL_EXEMPT", "ENABLE_FLEET_OVERLOAD_PENALTY",
 "ENABLE_OBJ_SPAN_COST", "ENABLE_BEST_EFFORT_FASTEST_PICKUP_SHADOW"]


def flag_live(name):
    try:
        return C.flag(name, "??")
    except Exception:
        return FLAGS.get(name, "<not in flags.json; code-default>")


print("=" * 70 + "\nLIVE CONSTANTS (getattr on imported common; env overrides NONE per systemctl show)\n" + "=" * 70)
for fam, names in CONSTS.items():
    print(f"\n--- {fam} ---")
    for nm in names:
        v = getattr(C, nm, "<<MISSING>>")
        print(f"  {nm:42s} = {v!r}")

# dict-valued tables
for tbl in ["DWELL_BY_TIER", "V326_SPEED_TIER_MULT", "SPEED_TIER_MULT", "V326_OSRM_TRAFFIC_TABLE",
            "TIER_SPEED_MULT", "V3273_WAIT_PENALTY_TABLE", "V327_WAIT_PENALTY_TABLE"]:
    v = getattr(C, tbl, None)
    if v is not None:
        print(f"\n  {tbl} = {json.dumps(v, ensure_ascii=False, default=str)[:600]}")

print("\n" + "=" * 70 + "\nLIVE FLAGS (C.flag → flags.json hot-reload)\n" + "=" * 70)
for nm in FLAGNAMES:
    print(f"  {nm:46s} = {flag_live(nm)}")

# discover any SPEED/MULT names we may have missed
print("\n--- dir(C) names containing SPEED/MULT/DWELL/WAIT ---")
hits = [n for n in dir(C) if any(t in n for t in ("SPEED", "MULT", "DWELL", "WAIT_COURIER")) and n.isupper()]
print("  ", hits)
print("\nDONE")
