#!/usr/bin/env python3
"""SCRIPT 5 — Build markdown root-cause report from scripts 1-4 outputs.

Run scripts 1-4 with stdout captured to logs/sprint2_<script>.txt, then
this script glues them into data/sprint2_root_cause_<DATE>.md.
"""
import argparse
from datetime import date
from pathlib import Path

HERE = Path(__file__).parent
LOGS = HERE / "logs"
DATA = HERE / "data"


def read_or_placeholder(path):
    if path.exists():
        return path.read_text()
    return f"_(missing — run upstream script first: {path.name})_\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=date.today().isoformat())
    args = ap.parse_args()

    inv = read_or_placeholder(LOGS / "sprint2_data_inventory.txt")
    tak = read_or_placeholder(LOGS / "sprint2_tak_mystery.txt")
    ovr = read_or_placeholder(LOGS / "sprint2_override_patterns.txt")
    upt = read_or_placeholder(LOGS / "sprint2_propose_uptime.txt")

    md = f"""# Sprint 2 Root Cause Analysis — {args.date}

## Executive Summary

- **Verdict:** _(fill from uptime + override + tak_mystery convergence)_
- **Recommended Sprint 3 priorities (top 3):**
  1. _(from override_patterns Sprint 3 priority list)_
  2. _(from override_patterns Sprint 3 priority list)_
  3. _(from override_patterns Sprint 3 priority list)_
- **Critical concerns:** _(uptime VERDICT below; if C → all override analysis is over-indexed on the small windows that DID propose)_

---

## Data Inventory

```
{inv.strip()}
```

---

## TAK=0 Mystery

```
{tak.strip()}
```

---

## Override Patterns (top 7)

```
{ovr.strip()}
```

---

## Propose Flow Uptime (NEW dimension)

```
{upt.strip()}
```

---

## Sprint 3 Recommendations

1. _(highest-priority fix with effort + risk; reference Sprint 3 priority list above)_
2. _(2nd priority)_
3. _(3rd priority)_

## V3.28 Tickets to Plan

- **panel_client default OFF** — per-service env override audit (cross-ref Lekcja #47)
- **session pool architecture** — eliminate CSRF collision once-and-for-all (cross-ref feedback_panel_session_singleton)
- **propose flow monitoring** — alert if gap > 5 min between successive proposes during peak (driven by SCRIPT 4 findings today)

---

_Generated by report_builder.py from offline analysis. Live services untouched per HARD RULE C.1._
"""

    DATA.mkdir(exist_ok=True)
    out = DATA / f"sprint2_root_cause_{args.date}.md"
    out.write_text(md)
    print(f"Report written: {out}")


if __name__ == "__main__":
    main()
